version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: todo_postgres_db
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass      
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: todo_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: