services:
  postgres:
    image: postgres:13
    container_name: todo_postgres_db
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - signoz-net
  
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: todo_postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://todouser:todopass@postgres:5432/tododb?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - signoz-net

  redis:
    image: redis:7
    container_name: todo_redis
    ports:
      - "6379:6379"
    networks:
      - signoz-net
  
  redis-exporter:
    image: oliver006/redis_exporter:v1.37.0
    container_name: todo_redis_exporter
    environment:
      REDIS_ADDR: "redis:6379"
    ports:
      - "9121:9121"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - signoz-net

  flask-app:
    build: ./app
    container_name: todo_flask_app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tododb
      DB_USER: todouser
      DB_PASSWORD: todopass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OTEL_SERVICE_NAME: flask-todo-app
    networks:
      - signoz-net
 
networks:
  signoz-net:
    external: true

volumes:
  postgres_data: