# Prometheus configuration for SigNoz
global:
  scrape_interval: 5s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093

rule_files:
  - 'alerts.yml'

scrape_configs: []

remote_read:
  - url: tcp://clickhouse:9000/signoz_metrics